---
- name: Rebuild Debian ssmtp database
  command: dpkg-reconfigure ssmtp -f noninteractive -p critical
  become: true

- name: Rebuild Debian msmtp database
  command: dpkg-reconfigure msmtp -f noninteractive -p critical
  become: true
- name: OpenSMTPd restart
  systemd:
    name: opensmtpd
    state: restarted
  become: true
