---
- name: Update motd
  template:
    src: "motd.j2"
    dest: "/etc/motd"
    owner: "root"
    group: "root"
    mode: "0644"
  become: true

- name: "Update bashrc: colour prompt"
  lineinfile:
    path: "/etc/bash.bashrc"
    regexp: "force_color_prompt=yes"
    line: "force_color_prompt=yes"
    state: present
    insertafter: EOF
  when:
    - basics_colorprompt | bool
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  become: true

- name: "Update profile: colour prompt (RedHat)"
  copy:
    src: templates/color_prompt.sh
    dest: /etc/profile.d/color_prompt.sh
    owner: root
    group: root
    mode: '0644'
  when:
    - basics_colorprompt | bool
    - ansible_os_family == "RedHat"
  become: true

- name: Remove cloud-init
  package:
    name: cloud-init
    state: absent
  become: true

- name: Remove cloud-init local data
  file:
    path: /etc/cloud
    state: absent
  become: true

- name: Remove cloud-init system data
  file:
    path: /var/lib/cloud
    state: absent
  become: true
