---
- name: Install opensmtpd
  package:
    name: '{{ nullmailer_opensmtpd_packages }}'
    state: present
  become: true

- name: Set deault MTA to opensmtpd
  command: /usr/sbin/alternatives --set mta /usr/sbin/sendmail.opensmtpd
  become: true

- name: Change config file
  template:
    src: 'smtpd.conf.j2'
    dest: '/etc/opensmtpd/smtpd.conf'
    owner: 'root'
    group: 'root'
    mode: '0640'
  notify: 'OpenSMTPd restart'
  become: true

- name: Configure aliases
  template:
    src: 'aliases.j2'
    dest: '/etc/aliases'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'OpenSMTPd restart'
  become: true

- name: enable opensmtpd service
  systemd:
    name: opensmtpd
    enabled: yes
  become: true
