---
- name: Include distribution specific variables
  include_vars: "vars-dist-{{ ansible_facts.distribution }}.yml"

- name: Make sure the default sources.lists file exists
  ansible.builtin.file:
    path: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644
    state: touch
    modification_time: preserve
    access_time: preserve
  become: true

- name: Comment out all sources in default sources.list file
  replace:
    path: /etc/apt/sources.list
    regexp: '^\s*(deb .*)'
    replace: '#\1'
  become: true

- name: Configure APT repositories
  apt_repository:
    filename: 'ansible'
    update_cache: '{{ apt_update_cache }}'
    repo: '{{ item.repo }}'
    state: '{{ item.state }}'
  with_items: '{{ apt_repositories }}'
  become: true

- name: Upgrade packages
  apt:
    update_cache: '{{ apt_update_cache }}'
    upgrade: '{{ apt_upgrade }}'
    autoclean: '{{ apt_autoclean }}'
    autoremove: '{{ apt_autoremove }}'
    force_apt_get: '{{ apt_force_apt_get }}'
  become: true
