---
- name: Include distribution specific variables
  include_vars: "vars-dist-{{ ansible_facts.distribution }}.yml"

- name: Remove default sources.list file
  file:
    path: /etc/apt/sources.list
    state: absent
  become: true

- name: Configure APT repositories
  apt_repository:
    filename: 'ansible'
    update_cache: '{{ apt_update_cache }}'
    repo: '{{ item.repo }}'
    state: 'present'
  with_items: '{{ apt_repositories }}'
  become: true

- name: Upgrade packages
  apt:
    update_cache: '{{ apt_update_cache }}'
    upgrade: '{{ apt_upgrade }}'
    autoclean: '{{ apt_autoclean }}'
    autoremove: '{{ apt_autoremove }}'
    force_apt_get: '{{ apt_force_apt_get }}'
  become: true
