---
- name: List of base language packs
  set_fact: languagesupport_basepack='langpacks-{{ item.split('_')[0] }}'
  loop: "{{ languagesupport_locales|flatten(levels=1) }}"
  register: languagesupport_basepacks

- name: Install base language pack(s)
  package:
    name: "{{ languagesupport_basepacks.results | map(attribute='ansible_facts.languagesupport_basepack') | list }}"
    state: present
  become: true

- name: Set default language pack
  command: localectl set-locale "{{ languagesupport_default }}"
  become: true
