---
- name: install needed network manager libs
  package:
    name:
      - NetworkManager-libnm
      - nm-connection-editor
      - python3-libsemanage
      - python3-policycoreutils
    state: present
  become: true

- name: Configure interface(s)
  nmcli:
    type: ethernet
    conn_name: '{{ item.conn_name }}'
    ifname: '{{ item.ifname }}'
    ip4: '{{ item.ip4 }}'
    gw4: '{{ item.gw4 }}'
    dns4: '{{ item.dns4 }}'
    dns4_search: '{{ item.dns4_search }}'
    state: present
  with_items:
    - '{{ nmcli_int }}'
  become: true

- name: Reload interface(s)
  command: nmcli con up '{{ item.conn_name }}'
  with_items:
    - '{{ nmcli_int }}'
  become: true
