galaxy_info:
  author: SmartOps.Academy
  description: Installs and configures a nullmailer.
  company: SmartOps Academy

  license: CC-BY-SA

  min_ansible_version: 2.4

  github_branch: https://github.com/SmartOpsAcademy/ansible/roles/nullmailer

  platforms:
    - name: Debian
      versions:
        - jessie
        - stretch
        - buster
    - name: Ubuntu
      versions:
        - bionic
        - focal

  galaxy_tags:
    - debian
    - ubuntu
    - nullmailer
    - ssmtp

dependencies: []
